server.port: 8080

spring:
  application:
    name: ${artifactId}
  profiles:
    include: security
  datasource:
    url:
    driver-class-name:
    username:
    password:
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: false
        format_sql: false
        use_sql_comments: true
        generate_statistics: true
        jdbc.batch_size: 30
        order_inserts: true
        cache.use_second_level_cache: false
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml

camel:
  springboot:
    name: ${spring.application.name}-camel
    main-run-controller: true
    #    java-routes-exclude-pattern: "**/SomeRoute01*, **/SomeRoute02*"
    #    java-routes-include-pattern: "**/SomeRoute03*, **/SomeRoute04*"
    shutdown-timeout: 60

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
  api-docs:
    path: /api-docs
  packagesToScan: ${basePackage}.resource
  pathsToMatch: 

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jasypt.encryptor.password: 

logging.level:
  ROOT: INFO
  org.springframework: DEBUG
  org.springframework.boot.autoconfigure.logging: INFO
  ${basePackage}: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
